<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>

<div class="page-title">
    <h1>Create new ticket</h1>
</div>

<form action="<?php echo $this->getSaveUrl(); ?>" id="ticketForm" method="post">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Ticket Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="subject" class="required"><em>*</em><?php echo Mage::helper('inchoo_ticketmanager')->__('Subject') ?></label>
                    <div class="input-box">
                        <input name="subject" id="subject" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('inchoo_ticketmanager')->__('Subject')) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
            </li>
            <li class="wide">
                <label for="message" class="required"><em>*</em><?php echo Mage::helper('inchoo_ticketmanager')->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('inchoo_ticketmanager')->__('Message')) ?>" class="required-entry input-text" cols="5" rows="5"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>
</form>

<script type="text/javascript">
    //<![CDATA[
    var ticketForm = new VarienForm('ticketForm', true);
    //]]>
</script>